dnd/character/urls.py
from django.urls import path

from . import views

app_name = "character"

urlpatterns = [
    path("save", views.save, name="save"),
    path("", views.load, name="load")
]

dnd/dnd/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('character/', include("character.urls")),
    path('', include("index.urls")),
    path('monster/', include("monster.urls")),
    path('rte/', include("rte.urls")),
    path('encounter/', include("encounter.urls"))
]

dnd/monster/urls.py
from django.urls import path

from . import views

app_name = "monster"

urlpatterns = [
    path("save", views.save, name="savemon"),
    path("", views.load, name="loadmon")
]

dnd/rte/urls.py
from django.urls import path

from . import views

app_name = "rte"

urlpatterns = [
    path("save/", views.table, name="table"),
    path("", views.loadrte, name="loadrte"),
    path("initiative", views.prepcomb, name="prepcomb")
]

dnd/index/templates/index/about.html
{% extends "index/layout.html" %}
{% block title %}
    About
{% endblock %}
{% block main %}
<div class="container bg-light bg-opacity-50">
<p>Hi! Art here!</p>
<p>I'm a 28 year old dentistry student currently living in Madrid.</p>
<p>My passion has always been engineer-oriented. Never had the oportunity to do so, but with this course I was able to at least introduce myself 
to the world of computer science. I cannot be happier! I have come such a long way since I first started.
</p>
<p>If for whatever reason you are reading this, don't be discoraged to continue. In the end it will all be worth it! I promise.</p>
<p>My coding related address is: artsanchezgarcia@gmail.com</p>
<p>Contact me if you need help with this course!</p>
</div>

{% endblock %}

dnd/index/templates/index/index.html
{% extends "index/layout.html" %}
{% block title %}
    Index
{% endblock %}
{% block main %}
{% load static %}
    <div class="container">
        <div class="row">
            <div class="col">
                <div class="card bg-dark bg-opacity-25">
                    <img style="width: 350px; height: auto;" src="{% static 'rte.jpg' %}" class="card-img-top" alt="Xanathar">
                  
                    <div class="card-body bg-light bg-opacity-25">
                        <h5 class="card-title">Encounter Tables</h5>
                        <p class="card-text">Here you can select a Random Table of monsters and  start combat.</p>
                        <a href="{% url 'rte:loadrte' %}" class="btn btn-primary bg-dark bg-opacity-50">Random table encounters</a>
                    </div>
                    <div class="card-body bg-light bg-opacity-25">
                        <h5 class="card-title">Create New Random Table Encounter</h5>
                        <p class="card-text">Here you can create your own random encounter tables.</p>
                        <a href="{% url 'rte:table' %}" class="btn btn-primary bg-dark bg-opacity-50">Create table</a>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card bg-dark bg-opacity-25">
                    <img style="width: 350px; height: auto;" src="{% static 'monster.jpg' %}" class="card-img-top" alt="Strahd">
                  
                    <div class="card-body bg-light bg-opacity-25">
                        <h5 class="card-title">List of Monsters</h5>
                        <p class="card-text">In this section you can see a list of all monsters and their respective stats in the database.</p>
                        <a href="{% url 'monster:loadmon' %}" class="btn btn-primary bg-dark bg-opacity-50">Monster</a>
                    </div>
                    <div class="card-body bg-light bg-opacity-25">
                        <h5 class="card-title">Create Monster</h5>
                        <p class="card-text">Here you can create monsters so you can add them later to encounter tables.</p>
                        <a href="{% url 'monster:savemon' %}" class="btn btn-primary bg-dark bg-opacity-50">Create Monster</a>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card bg-dark bg-opacity-25">
                    <img style="width: 350px; height: auto;" src="{% static 'character.jpg' %}" class="card-img-top" alt="Ajani">
                  
                    <div class="card-body bg-light bg-opacity-25">
                        <h5 class="card-title">List of characters</h5>
                        <p class="card-text">Here you can see your players' characters stats.</p>
                        <a href="{% url 'character:load' %}" class="btn btn-primary bg-dark bg-opacity-50">Character</a>
                    </div>
                    <div class="card-body bg-light bg-opacity-25">
                        <h5 class="card-title">Create New Character</h5>
                        <p class="card-text">Here you can create new characters so you can access their info in the combat UI.</p>
                        <a href="{% url 'character:save' %}" class="btn btn-primary bg-dark bg-opacity-50">Save Character</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <div class="card bg-dark bg-opacity-25">
                  

                </div>
            </div>
            <div class="col">
                <div class="card bg-dark bg-opacity-25">
                  

                </div>
            </div>
            <div class="col">
                <div class="card bg-dark bg-opacity-25">
                  

                </div>
            </div>
        </div>
    </div>      
{% endblock %}

dnd/index/templates/index/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
        <link rel="stylesheet" href="{% static 'styles.css' %}">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

    </head>

    <body class="bg-dark bg-opacity-75">
        <nav class="navbar navbar-expand-lg bg-dark bg-opacity-75">
            <div class="container-fluid">
                <a class="navbar-brand text-white" href="/">Home</a>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                      <li class="nav-item">
                        <a class="nav-link active text-white" aria-current="page" href="{% url 'character:load' %}">Character</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link active text-white" aria-current="page" href="{% url 'monster:loadmon' %}">Monster</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link active text-white" aria-current="page" href="{% url 'rte:loadrte' %}">Encounter Tables</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link text-white" aria-current="page" href="/about">About</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link text-white" aria-current="page" href="/admin/">Admin</a>
                      </li>
                    </ul>
                </div>
            </div>
        </nav>

        <main>
            {% block main %}{% endblock %}
        </main>
    </body>
</html>