dnd/dnd/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('character/', include("character.urls")),
    path('', include("index.urls")),
    path('monster/', include("monster.urls")),
    path('rte/', include("rte.urls")),
    path('encounter/', include("encounter.urls"))
]

dnd/encounter/urls.py
from django.urls import path

from . import views

app_name = "encounter"

urlpatterns = [
    path("", views.combat, name="combat")
]

dnd/rte/urls.py
from django.urls import path

from . import views

app_name = "rte"

urlpatterns = [
    path("save/", views.table, name="table"),
    path("", views.loadrte, name="loadrte"),
    path("initiative", views.prepcomb, name="prepcomb")
]

dnd/rte/models.py
from django.db import models
from django import forms
from django.forms import ModelForm, formset_factory
from monster.models import Monster 

# Create your models here.
class RTE(models.Model):
    tablename = models.CharField(max_length=100, unique=True)
    tablemons = models.TextField()

    def __str__(self):
        return self.tablename

dnd/rte/views.py
from django import forms
from django.http import HttpResponseRedirect, request
from django.shortcuts import render
from django.urls import reverse
from django.forms import ModelForm, formset_factory
from monster.models import Monster
from character.models import Character
from .models import RTE
import random

DICE_CHOICE = ['None', 'd4', 'd6', 'd8', 'd10', 'd12']
# create table f(x)
def table(request):
    rows = range(1, 19)
    monsterlist = Monster.objects.all()
    if request.method == "POST":
        tablename = request.POST.get('tablename')
        if not tablename:
            failure = 'Provide a tablename'
            context = {'range': rows, 'monsters': monsterlist, 'dices': DICE_CHOICE, 'failure': failure}
            return render(request, "rte/table.html", context)
            
        if RTE.objects.filter(tablename=tablename).exists():
            failure = 'Tablename already in use'
            context = {'range': rows, 'monsters': monsterlist, 'dices': DICE_CHOICE, 'failure': failure}
            return render(request, "rte/table.html", context)

        fintab = [tablename]
        for info in rows:
            numd = 'nod' + str(info)
            typed = 'dice' + str(info)
            monsd = 'monster' + str(info)
            nod = request.POST.get(numd)
            dice = request.POST.get(typed)
            monster = request.POST.get(monsd)
            if dice == 'None':
                apinfo = nod + ' ' + monster
            else:
                apinfo = nod + dice + ' ' + monster

            fintab.append(apinfo)
        
        rte = RTE(tablename=fintab[0], tablemons=fintab)
        rte.save()
        return HttpResponseRedirect(reverse("rte:loadrte"))

    context = {
        'range': rows,
        'monsters': monsterlist,
        'dices': DICE_CHOICE
    }
    return render(request, "rte/table.html", context)

# save table f(x)

def loadrte(request):
    # tengo una lista vacia
    finaltables = []
    # saco una lista con las listas de los mostros de la db, las cuales tienen 1 elemento
    tables = RTE.objects.values_list('tablemons')
    # para cada una de esas listas:
    for table in tables:
        # les quito los dos primeros y ultimos caracteres y hago una lista con cada uno de los elementos (por cada "', '")
        xtable = table[0].replace("['", "").replace("']", "").split("', '")
        # la lista creada la añado a la lista que se enviara al html
        finaltables.append(xtable)
    # para cada tabla en la tabla que se enviara
    for list in finaltables:
        # esto deberia sustituir la id del mostro por el nombre del mostro
        listmon(list)
# tratar el texto que sale para que sea tratable por el template
    context = {
        'tables': finaltables
    }
    return render(request, "rte/index.html", context) 
    
# iniciativa 
def prepcomb(request):
    if request.method == "POST":
        
        table = request.POST.get('table')   
        stable = int(table) - 1
        tablemons = RTE.objects.values_list('tablemons')[stable]
        tablemons = tablemons[0].replace("['", "").replace("']", "").split("', '")
        
        listmon(tablemons)

        calcdicemon = []
        chomon(calcdicemon, tablemons)

        chars = Character.objects.values_list('charname')

        context = {'enemies': calcdicemon, 'characters': chars}
        return render(request, "rte/prepcomb.html", context)


def chomon(emptylist, list):
    tabledice = random.randint(1, 10) + random.randint(0, 7)
    item = list[tabledice]
    mon = item.rsplit(None, 1)[-1]
    emptylist.append(mon)

    mondice = item.split(None, 1)[0]
    if 'd' in mondice:
        xdice = mondice.split('d', 1)
        dice = int(xdice[0]) * random.randint(1, int(xdice[1]))
        emptylist.append(dice)
    else:
        emptylist.append(mondice)

def listmon(list):    
    i = 1
    # para cada item de la lista que le han pasado empezando por el segundo item
    for monster in list[1:]:
        # esto saca el ultimom item, es decir la id del mostro
        mondb = monster.rsplit(None, 1)[-1]
        # esto busca el mostro que coincide con dicha id
        monshow = Monster.objects.get(pk=int(mondb))
        # en el caso de encontrar un mostro con esa id
        if Monster.objects.get(pk=int(mondb)):
            # esto convierte el item de la lista en #d## # en #d## moname
            monster = monster.split(None, 1)[0] + ' ' + monshow.moname
            list[i] = monster
        i = i + 1


# calcular que mostro y cuantos y que calcule el iniciativa de mostros y pida iniciativa de jugadores
# quiza con un formulario de pjs activos?

# con el dado puedo hacer una funcion recursiva
# pillas el numero de dados
# def rte(y, x)
#   if 'y' > 1:
#       rte(y-1, x)
#   else:
#       return randomnumber between 1 and x
# algo asi

dnd/rte/templates/rte/index.html
{% extends "index/layout.html" %}
{% block title %}
    Index Tables
{% endblock %}
{% block main %}
<h1 class="text-center bg-light bg-opacity-25">CHOOSE YOUR TABLE</h1>
<form class="text-center" action="{% url 'rte:prepcomb' %}" method="post">
    {% csrf_token %}
    <select class="bg-secondary" name="table" id="table" type="text">
        <option>Choose a table</option>
        {% for table in tables %}
        <option value="{{ forloop.counter }}">{{ table.0 }}</option>
        {% endfor %}
    </select>
    <button class="bg-dark bg-opacity-25" type="submit">Combat!</button>
</form>

<div class="container container-fluid text-opacity-50">
    <div class="" id="0" style="display: block"></div>
    {% for table in tables %}
    <div class="hidden" id="{{ forloop.counter }}" style="display: none">
        {% for item in table %}
            <div class="text-center">{{ item }}</div>
        {% endfor %}
    </div>
    {% endfor %}
</div>
<script>
    document.getElementById('table').onchange = function() {
        var i = 1;
        var myDiv = document.getElementById(i);
        while(myDiv) {
            myDiv.style.display = 'none';
            myDiv = document.getElementById(++i);
        }
        document.getElementById(this.value).style.display = 'block';
    };
</script>

{% endblock %}

dnd/rte/templates/rte/prepcomb.html
{% extends "index/layout.html" %}
{% block title %}
    Iniciative!!!
{% endblock %}
{% block main %}
<h1 class="text-center bg-light bg-opacity-25">ROLL FOR INITIATIVE</h1>
<div class="text-center py-3">You are going to fight: {{ enemies.1 }} {{ enemies.0 }}</div>

<div class="container py-3">
    <form class="text-center" action="{% url 'encounter:combat' %}" method="post">
        {% csrf_token %}
        <div class="">
            <label for="noe">Nº of enemies</label>
            <input type="number" name="numenemy" value="{{ enemies.1 }}">

            <label for="typenemy">Enemy Type</label>
            <input type="text" name="typenemy" value="{{ enemies.0 }}" readonly>
        </div>

        <div class="py-3">
            {% for character in characters %}
            <div class="py-3">
            {{ character.0 }}
            <input type="number" name="ini{{ forloop.counter }}">
            </div>
            {% endfor %}
        </div>
        <input type="submit" value="Combat!">
    </form>
</div>

{% endblock %}

dnd/rte/templates/rte/table.html
{% extends "index/layout.html" %}
{% block title %}
    Create Tables
{% endblock %}
{% block main %}

<h1 class="text-center bg-light bg-opacity-25">Create a table of 18 slots</h1>
<h2 class="text-center bg-light bg-opacity-25">{{ failure }}</h2>

<form class="text-center" action="{% url 'rte:table' %}" method="post">
    {% csrf_token %}
    <table class="table table-hover table-responsive">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Number of monsters</th>
                <th scope="col">Monster</th>
            </tr>
        </thead>
        <tbody>
        {% for number in range %}
            <tr class="table-dark">
                <td>
                   {{ forloop.counter }} 
                </td>

                <td>
                    <input type="number" min="1" max="5" value="1" name="nod{{ forloop.counter }}">
                    <select class="bg-secondary" name="dice{{ forloop.counter }}">
                    {% for dice in dices %}
                        <option value="{{ dice }}">{{ dice }}</option>
                    {% endfor %}
                </td>

                <td>
                    <select class="bg-secondary" name="monster{{ forloop.counter }}" type="text">
                    {% for monster in monsters %}
                        <option value="{{ monster.id }}">{{ monster.moname }}</option>
                    {% endfor %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
        <input type="text" placeholder="Name your encounter table" name="tablename">
        <input value="Create" type="submit">
</form>
{% endblock %}